# Generated by Django 3.2.9 on 2023-11-10 16:53

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('username', models.CharField(max_length=32, unique=True, verbose_name='아이디')),
                ('useremail', models.EmailField(max_length=128, unique=True, verbose_name='이메일')),
                ('phone', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(regex='^01([0|1|6|7|8|9]?)-?([0-9]{3,4})-?([0-9]{4})$')], verbose_name='전화번호')),
                ('name', models.CharField(max_length=10, verbose_name='사용자 이름')),
                ('agency', models.CharField(blank=True, max_length=100, null=True, verbose_name='대행코드')),
                ('password', models.CharField(max_length=256, verbose_name='비밀번호')),
                ('money_point', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(10000)], verbose_name='보유 포인트')),
                ('point_volume', models.IntegerField(default=0, verbose_name='총 사용 포인트')),
                ('point_plus', models.IntegerField(default=0, verbose_name='총 충전 포인트')),
                ('point_minus', models.IntegerField(default=0, verbose_name='총 환불 포인트')),
                ('shopping_price', models.IntegerField(default=200, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(10000)], verbose_name='N 쇼핑클릭 단가')),
                ('place_save_price', models.IntegerField(default=200, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(10000)], verbose_name='N 플레이스 저장하기 단가')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용가능 여부')),
                ('is_agency', models.BooleanField(default=False, verbose_name='대행사 여부')),
                ('is_admin', models.BooleanField(default=False, verbose_name='어드민 여부')),
                ('is_staff', models.BooleanField(default=False, verbose_name='스텝여부 여부')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='슈퍼관리자 여부')),
                ('last_login', models.DateTimeField(auto_now_add=True, verbose_name='마지막 로그인 시간')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '고객 리스트',
                'verbose_name_plural': '고객 리스트',
            },
        ),
    ]
