# Generated by Django 3.2.9 on 2024-06-15 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_agency',
        ),
        migrations.RemoveField(
            model_name='account',
            name='place_save_price',
        ),
        migrations.RemoveField(
            model_name='account',
            name='point_minus',
        ),
        migrations.RemoveField(
            model_name='account',
            name='point_plus',
        ),
        migrations.RemoveField(
            model_name='account',
            name='point_volume',
        ),
        migrations.RemoveField(
            model_name='account',
            name='shopping_price',
        ),
        migrations.AlterField(
            model_name='account',
            name='money_point',
            field=models.IntegerField(default=0, verbose_name='보유 포인트'),
        ),
    ]
